pipeline {
    agent any
    stages {
        stage('Initialize'){
            steps{
                bat "java -version"
                bat "mvn -version"
            }
        }
        stage('Build') {
            steps {
                // Get code from a GitHub repository
                git branch: 'main', url: 'https://github.com/restuputra3007/belajar.build.jenkins.git';
               echo 'Build';
               //"mvn clean install package assembly:single";
            }
        }
        stage('Run') {
            steps {
                echo 'Run';
                //'java -jar .\target\belajar.build.jenkins-1.0-SNAPSHOT-jar-with-dependencies.jar'
            }
        }
    }
}
