pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                // Get code from a GitHub repository
               //echo 'Build';
               'mvn clean install package assembly:single'
            }
        }
        stage('Run') {
            'java -jar .\target\belajar.build.jenkins-1.0-SNAPSHOT-jar-with-dependencies.jar'
        }
    }
}
